### ISSUE TITLE
test core::exchanges::exchange_blocker::tests::block_many_times_with_stop_exchange_blocker ... FAILED

### ISSUE THREAD

**Issue by jgarzik** [purefinance/mmb#27]
Testing with `cargo test` passes.
Testing with `cargo test --release` fails.

OS:  MacOS
Platform:
```
$ rustc --version
rustc 1.50.0 (cb75ad5db 2021-02-10)
```

```
test core::exchanges::exchange_blocker::tests::block_with_first_long_handler ... ok
test core::exchanges::exchange_blocker::tests::block_duration ... ok
test core::exchanges::exchange_blocker::tests::reblock_before_time_is_up ... ok
test core::exchanges::exchange_blocker::tests::block_many_times_with_stop_exchange_blocker ... FAILED
test core::connectivity::connectivity_manager::tests::should_connect_and_reconnect_normally ... ok
test core::connectivity::websocket_actor::tests::connect_and_send_msg ... ok

failures:

---- core::exchanges::exchange_blocker::tests::block_many_times_with_stop_exchange_blocker stdout ----
thread 'core::exchanges::exchange_blocker::tests::block_many_times_with_stop_exchange_blocker' panicked at 'Timeout was exceeded (2000 ms)', src/core/exchanges/exchange_blocker.rs:1147:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    core::exchanges::exchange_blocker::tests::block_many_times_with_stop_exchange_blocker

test result: FAILED. 44 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.74s

error: test failed, to rerun pass '--lib'
```

**Comment by jgarzik** [comment]
With backtrace:
```

failures:

---- core::exchanges::exchange_blocker::tests::block_many_times_with_stop_exchange_blocker stdout ----
thread 'core::exchanges::exchange_blocker::tests::block_many_times_with_stop_exchange_blocker' panicked at 'Timeout was exceeded (2000 ms)', src/core/exchanges/exchange_blocker.rs:1147:39
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:435:5
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   3: tokio::macros::scoped_tls::ScopedKey<T>::set
   4: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
   5: tokio::runtime::Runtime::block_on
   6: mmb_lib::core::exchanges::exchange_blocker::tests::block_many_times_with_stop_exchange_blocker
   7: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    core::exchanges::exchange_blocker::tests::block_many_times_with_stop_exchange_blocker

test result: FAILED. 44 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.77s

error: test failed, to rerun pass '--lib'
```
